### ISSUE TITLE
Failing with: Can not run as root in Jenkins environment

### ISSUE THREAD

**Issue by ssouris** [allegro/embedded-elasticsearch#35]
When trying to run on our Jenkins CI environment I get this exception.
Is there a workaround?

`
17:59:19.797 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Download skipped
17:59:19.797 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Installing Elasticsearch into /tmp/embedded-elasticsearch-temp-dir...
17:59:20.926 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Done
17:59:20.930 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Applying executable permissions on /tmp/embedded-elasticsearch-temp-dir/elasticsearch-5.5.2/bin/elasticsearch-plugin
17:59:20.930 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Applying executable permissions on /tmp/embedded-elasticsearch-temp-dir/elasticsearch-5.5.2/bin/elasticsearch
17:59:20.930 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller - Applying executable permissions on /tmp/embedded-elasticsearch-temp-dir/elasticsearch-5.5.2/bin/elasticsearch.in.sh
17:59:20.931 [Test worker] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - Waiting for ElasticSearch to start...
17:59:23.205 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - [2017-11-08T17:59:23,191][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
17:59:23.205 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
17:59:23.205 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.206 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.206 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.206 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.206 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.206 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - Caused by: java.lang.RuntimeException: can not run elasticsearch as root
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:106) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.207 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
17:59:23.208 [EmbeddedElsHandler] INFO pl.allegro.tech.embeddedelasticsearch.ElasticServer - 	... 6 more
`

**Comment by ssouris** [comment]
Apparently this is not an issue of this library. 
Elasticsearch cannot be run as root and that is something that is hardcoded into the code after 5.0.0 release (approximately).
Closing.
