### ISSUE TITLE
Permission denied Exception while Running Embedded ElasticSearch 

### ISSUE THREAD

**Issue by neerajjain92** [allegro/embedded-elasticsearch#90]
After fixing issue #89, I ended up in this problem.  **Permission Denied**

My EmbeddedElastic configuration is : 
```
@BeforeClass
public static void setup() {
 final EmbeddedElastic embeddedElastic = EmbeddedElastic.builder()
 .withElasticVersion("6.6.0")
 .withSetting(PopularProperties.TRANSPORT_TCP_PORT, "9200")
 .withSetting(PopularProperties.CLUSTER_NAME, "partner_portal_elasticsearch_cluster")
 .withPlugin("analysis-stempel") // Commented this line, with this line permission deined came while installing the plugin
  .build();

     try {
         embeddedElastic.start();
        System.out.println("Embedded Elastic Search instance started................");
     } catch (IOException e) {
         e.printStackTrace();
     } catch (InterruptedException e) {
        e.printStackTrace();
     }
  }
```
Here is the complete stack-trace.
```
Exception in thread "EmbeddedElsHandler" pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: java.io.IOException: Cannot run program "/var/folders/ql/403xvvqs42v00xlnqgr6d8540000gn/T/embedded-elasticsearch-temp-dir/elasticsearch-6.6.0/bin/elasticsearch": error=13, Permission denied
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.lambda$startElasticProcess$6(ElasticServer.java:89)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/var/folders/ql/403xvvqs42v00xlnqgr6d8540000gn/T/embedded-elasticsearch-temp-dir/elasticsearch-6.6.0/bin/elasticsearch": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.lambda$startElasticProcess$6(ElasticServer.java:80)
	... 1 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 3 more
```

**Comment by vivekkanda** [comment]
Any updates ?
